# Generated by Django 5.2.3 on 2025-06-17 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Assistant Oremi', max_length=100)),
                ('personality', models.TextField(default='Je suis un assistant virtuel bienveillant et professionnel.', help_text='Description de la personnalité du chatbot')),
                ('default_response', models.TextField(default='Je ne suis pas sûr de comprendre votre question. Pouvez-vous la reformuler ?', help_text='Réponse par défaut quand le chatbot ne comprend pas')),
                ('max_conversation_length', models.IntegerField(default=100, help_text='Nombre maximum de messages par conversation')),
                ('enable_emotion_detection', models.BooleanField(default=True)),
                ('enable_ai_generation', models.BooleanField(default=True)),
                ('ai_model_name', models.CharField(default='microsoft/DialoGPT-medium', help_text='Nom du modèle IA à utiliser', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration du chatbot',
                'verbose_name_plural': 'Configurations du chatbot',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='Catégorie de la question', max_length=100)),
                ('question', models.TextField(help_text='Question ou phrase clé')),
                ('answer', models.TextField(help_text='Réponse correspondante')),
                ('keywords', models.TextField(blank=True, help_text='Mots-clés associés (séparés par des virgules)')),
                ('confidence_threshold', models.FloatField(default=0.7, help_text='Seuil de confiance pour déclencher cette réponse')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Base de connaissances',
                'verbose_name_plural': 'Bases de connaissances',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='ID de session pour les utilisateurs anonymes', max_length=100)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_message_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, help_text='Utilisateur (optionnel pour les conversations anonymes)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'Utilisateur'), ('bot', 'Chatbot')], max_length=10)),
                ('content', models.TextField(help_text='Contenu du message')),
                ('detected_emotion', models.CharField(blank=True, choices=[('neutral', 'Neutre'), ('positive', 'Positif'), ('negative', 'Négatif'), ('angry', 'Colère'), ('sad', 'Tristesse'), ('joy', 'Joie'), ('fear', 'Peur'), ('surprise', 'Surprise')], help_text='Émotion détectée automatiquement', max_length=20, null=True)),
                ('emotion_confidence', models.FloatField(blank=True, help_text="Confiance dans la détection d'émotion (0-1)", null=True)),
                ('detected_language', models.CharField(blank=True, help_text='Langue détectée', max_length=10, null=True)),
                ('response_method', models.CharField(blank=True, choices=[('knowledge_base', 'Base de connaissances'), ('ai_generation', 'Génération IA'), ('fallback', 'Réponse par défaut')], help_text='Méthode utilisée pour générer la réponse', max_length=20, null=True)),
                ('processing_time', models.FloatField(blank=True, help_text='Temps de traitement en secondes', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.conversation')),
                ('knowledge_base_used', models.ForeignKey(blank=True, help_text='Base de connaissances utilisée pour cette réponse', null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.knowledgebase')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['timestamp'],
            },
        ),
    ]
