# Generated by Django 5.2.3 on 2025-06-17 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssuranceAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_residence', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=255)),
                ('date_obtention_permis', models.DateField()),
                ('categorie_socio_professionnelle', models.CharField(max_length=100)),
                ('immatriculation', models.CharField(max_length=20)),
                ('marque', models.CharField(max_length=50)),
                ('modele', models.CharField(max_length=50)),
                ('puissance_fiscale', models.DecimalField(decimal_places=2, max_digits=5)),
                ('numero_chassis', models.CharField(max_length=50, unique=True)),
                ('date_mise_circulation', models.DateField()),
                ('places_assises', models.IntegerField(help_text='Nombre de places assises')),
                ('carburation', models.CharField(choices=[('essence', 'Essence'), ('diesel', 'Diesel'), ('electrique', 'Électrique'), ('hybride', 'Hybride')], max_length=20)),
                ('valeur_achat', models.DecimalField(decimal_places=2, help_text="Valeur d'achat du véhicule", max_digits=10)),
                ('valeur_venale', models.DecimalField(decimal_places=2, help_text='Valeur vénale du véhicule', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='AssuranceHabitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(max_length=255)),
                ('type_logement', models.CharField(choices=[('appartement', 'Appartement'), ('maison', 'Maison'), ('studio', 'Studio'), ('villa', 'Villa')], max_length=50)),
                ('surface_habitable', models.DecimalField(decimal_places=2, help_text='Surface en m²', max_digits=6)),
                ('nombre_pieces', models.IntegerField()),
                ('nombre_chambres', models.IntegerField()),
                ('etage', models.IntegerField(blank=True, null=True)),
                ('annee_construction', models.IntegerField()),
                ('statut_occupant', models.CharField(choices=[('proprietaire', 'Propriétaire'), ('locataire', 'Locataire'), ('usufruitier', 'Usufruitier')], max_length=50)),
                ('systeme_securite', models.BooleanField(default=False)),
                ('alarme', models.BooleanField(default=False)),
                ('gardiennage', models.BooleanField(default=False)),
                ('valeur_mobilier', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valeur_immobilier', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='AssuranceMoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_residence', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=255)),
                ('date_obtention_permis', models.DateField()),
                ('type_permis', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('A', 'A')], max_length=10)),
                ('immatriculation', models.CharField(max_length=20)),
                ('marque', models.CharField(max_length=50)),
                ('modele', models.CharField(max_length=50)),
                ('cylindree', models.IntegerField(help_text='Cylindrée en cm³')),
                ('puissance', models.DecimalField(decimal_places=2, help_text='Puissance en kW', max_digits=5)),
                ('numero_chassis', models.CharField(max_length=50, unique=True)),
                ('date_mise_circulation', models.DateField()),
                ('valeur_achat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valeur_venale', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usage', models.CharField(choices=[('promenade', 'Promenade'), ('travail', 'Travail'), ('sport', 'Sport')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AssuranceSante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('profession', models.CharField(max_length=100)),
                ('situation_familiale', models.CharField(choices=[('celibataire', 'Célibataire'), ('marie', 'Marié(e)'), ('pacs', 'Pacsé(e)'), ('divorce', 'Divorcé(e)'), ('veuf', 'Veuf/Veuve')], max_length=50)),
                ('nombre_enfants', models.IntegerField(default=0)),
                ('antecedents_medicaux', models.TextField(blank=True, null=True)),
                ('traitements_en_cours', models.TextField(blank=True, null=True)),
                ('hospitalisation_recente', models.BooleanField(default=False)),
                ('formule', models.CharField(choices=[('essentielle', 'Essentielle'), ('confort', 'Confort'), ('premium', 'Premium')], max_length=50)),
                ('dentaire', models.BooleanField(default=False)),
                ('optique', models.BooleanField(default=False)),
                ('medecine_douce', models.BooleanField(default=False)),
                ('chambre_particuliere', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AssuranceVoyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('zone_geographique', models.CharField(choices=[('europe', 'Europe'), ('monde_sans_usa', 'Monde sans USA/Canada'), ('monde_entier', 'Monde entier')], max_length=50)),
                ('date_depart', models.DateField()),
                ('date_retour', models.DateField()),
                ('duree_sejour', models.IntegerField(help_text='Durée en jours')),
                ('motif_voyage', models.CharField(choices=[('tourisme', 'Tourisme'), ('affaires', 'Affaires'), ('etudes', 'Études'), ('sport', 'Sport'), ('visite_famille', 'Visite famille')], max_length=50)),
                ('nombre_voyageurs', models.IntegerField()),
                ('age_voyageur_principal', models.IntegerField()),
                ('voyageurs_seniors', models.BooleanField(default=False, help_text='Voyageurs de plus de 65 ans')),
                ('activites_sportives', models.BooleanField(default=False)),
                ('sports_extremes', models.BooleanField(default=False)),
                ('frais_medicaux_max', models.DecimalField(decimal_places=2, default=100000, max_digits=10)),
                ('rapatriement', models.BooleanField(default=True)),
                ('annulation', models.BooleanField(default=False)),
                ('bagages', models.BooleanField(default=False)),
                ('responsabilite_civile', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NPI', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('type_assurance', models.CharField(choices=[('auto', 'Auto'), ('moto', 'Moto'), ('habitation', 'Habitation'), ('sante', 'Santé'), ('voyage', 'Voyage')], max_length=50)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duree_couverture', models.IntegerField(help_text='Durée de la couverture en mois')),
                ('object_id', models.PositiveIntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devis.client')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
